name:                cli-table-tool
version:             0.1.0.0
github:              "sami-badawi/cli-table-tool"
license:             MIT
author:              "Sami Badawi"
maintainer:          "sami.badawi@gmail.com"
copyright:           "2020 Sami Badawi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            CLI tool to convert CLI tables to csv
# category:            CLI

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cli-table-tool#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  cli-table-tool:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cli-table-tool

tests:
  cli-table-tool-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cli-table-tool
